prioridad_maxima = [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Zaragoza",
    "Sevilla",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas de Gran Canaria",
    "Alicante",
    "Bilbao",
    "Córdoba",
    "Valladolid",
    "Vitoria-Gasteiz",
    "A Coruña",
]

prioridad_alta = [
    "Vigo",
    "Gijón",
    "L'Hospitalet de Llobregat",
    "Elche",
    "Terrassa",
    "Badalona",
    "Sabadell",
    "Oviedo",
    "Jerez de la Frontera",
    "Granada",
    "Pamplona",
    "Móstoles",
    "Santa Cruz de Tenerife",
    "Fuenlabrada",
    "Almería",
    "Alcalá de Henares",
    "Leganés",
    "San Sebastián",
    "Getafe",
    "Burgos",
    "Alcorcón",
    "Santander",
    "Albacete",
    "Castellón de la Plana",
    "Logroño",
    "Badajoz",
    "Salamanca",
    "Huelva",
    "Lleida",
    "Tarragona",
    "León",
    "Jaén",
    "Cádiz",
    "Ourense",
    "Girona",
    "Lugo",
    "Cáceres",
    "Guadalajara",
    "Melilla",
    "Toledo",
    "Ceuta",
    "Pontevedra",
    "Palencia",
    "Ciudad Real",
    "Zamora",
    "Ávila",
    "Huesca",
    "Cuenca",
    "Segovia",
    "Soria",
    "Teruel",
]

prioridad_media = [
    "San Cristóbal de La Laguna",
    "Marbella",
    "Dos Hermanas",
    "Algeciras",
    "Torrejón de Ardoz",
    "Parla",
    "Mataró",
    "Alcobendas",
    "Santa Coloma de Gramenet",
    "Reus",
    "Telde",
    "Barakaldo",
    "Las Rozas de Madrid",
    "Roquetas de Mar",
    "Rivas-Vaciamadrid",
    "San Sebastián de los Reyes",
    "El Puerto de Santa María",
    "Cornellà de Llobregat",
    "Pozuelo de Alarcón",
    "Sant Cugat del Vallès",
    "El Ejido",
    "San Fernando",
    "Torrent",
    "Chiclana de la Frontera",
    "Mijas",
    "Orihuela",
    "Torrevieja",
    "Sant Boi de Llobregat",
    "Vélez-Málaga",
    "Coslada",
    "Fuengirola",
    "Arona",
    "Getxo",
    "Manresa",
    "Rubí",
    "Alcalá de Guadaíra",
    "Gandía",
    "Molina de Segura",
    "Majadahonda",
    "Estepona",
    "Paterna",
    "Sanlúcar de Barrameda",
    "Sagunto",
    "Castelldefels",
    "Benidorm",
    "Viladecans",
    "Collado Villalba",
    "Granollers",
    "Irún",
    "Valdemoro",
    "Pinto",
]
