keywords_h1 = [
    "alquiler de maquinaria de construcción",
    "alquiler de maquinaria de obra civil",
    "alquiler de maquinaria pesada",
    "alquiler de maquinaria industrial",
    "alquiler de maquinaria para obra",
    "alquiler de maquinaria para reformas",
    "alquiler de maquinaria para excavaciones",
    "alquiler de maquinaria para movimiento de tierras",
    "alquiler de maquinaria para demolición",
    "alquiler de maquinaria para obras públicas",
    "alquiler de maquinaria para carreteras",
    "alquiler de maquinaria para urbanizaciones",
    "alquiler de maquinaria para proyectos industriales",
    "alquiler de maquinaria para construcción residencial",
    "alquiler de maquinaria para construcción comercial",
    "alquiler de maquinaria para naves industriales",
    "alquiler de maquinaria para infraestructuras",
    "alquiler de maquinaria para ingeniería civil",
    "alquiler de maquinaria para grandes obras",
    "alquiler de maquinaria para pequeñas obras",
    "alquiler de maquinaria para pavimentación",
    "alquiler de maquinaria para cimentaciones",
    "alquiler de maquinaria para túneles",
    "alquiler de maquinaria para puentes",
    "alquiler de maquinaria certificada para obra",
    "alquiler de maquinaria homologada para construcción",
    "alquiler de maquinaria homologada para obra",
    "alquiler de maquinaria certificada para construcción",
    "alquiler de maquinaria especializada para construcción",
    "alquiler de maquinaria para rehabilitación",
    "alquiler de maquinaria para instalaciones",
    "alquiler de equipos de construcción",
    "alquiler de equipos de obra civil",
    "alquiler de equipos industriales para construcción",
    "alquiler de equipos de maquinaria pesada",
    "alquiler de equipos pesados para obra",
    "alquiler profesional de maquinaria de construcción",
    "alquiler profesional de maquinaria industrial",
    "servicios de alquiler de maquinaria de construcción",
    "servicios de alquiler de maquinaria pesada",
    "empresas de alquiler de maquinaria de construcción",
    "empresas de alquiler de maquinaria industrial",
    "empresas de alquiler de maquinaria pesada",
    "empresas de alquiler de maquinaria de construcción",
    "empresas de alquiler de maquinaria industrial",
    "proveedores de alquiler de maquinaria de construcción",
    "proveedores de alquiler de maquinaria de obra civil",
    "proveedores de alquiler de maquinaria pesada",
    "proveedores de alquiler de maquinaria industrial",
    "proveedores de alquiler de maquinaria para obra",
    "proveedores de alquiler de maquinaria para reformas",
    "proveedores de alquiler de maquinaria para excavaciones",
    "proveedores de alquiler de maquinaria para movimiento de tierras",
    "proveedores de alquiler de maquinaria para demolición",
    "proveedores de alquiler de maquinaria para obras públicas",
    "proveedores de alquiler de maquinaria para carreteras",
    "proveedores de alquiler de maquinaria para urbanizaciones",
    "proveedores de alquiler de maquinaria para proyectos industriales",
    "proveedores de alquiler de maquinaria para construcción residencial",
    "proveedores de alquiler de maquinaria para construcción comercial",
    "proveedores de alquiler de maquinaria para naves industriales",
    "proveedores de alquiler de maquinaria para infraestructuras",
    "proveedores de alquiler de maquinaria para ingeniería civil",
    "proveedores de alquiler de maquinaria para grandes obras",
    "proveedores de alquiler de maquinaria para pequeñas obras",
    "proveedores de alquiler de equipos de construcción",
    "proveedores de alquiler de equipos de obra civil",
    "proveedores de alquiler de equipos de maquinaria pesada",
]

keywords_transaccionales = [
    "alquiler de excavadoras por días",
    "alquiler de grúas telescópicas",
    "alquiler de maquinaria construcción precio económico",
    "alquiler de retroexcavadoras para obra",
    "alquiler de plataformas elevadoras con operario",
    "alquiler de compactadoras vibratorias fin de semana",
    "alquiler de dumpers para construcción",
    "empresas de alquiler de maquinaria pesada cerca de mí",
    "alquiler de maquinaria industrial por horas",
    "alquiler de excavadora con transporte",
    "alquiler de palas cargadoras baratas",
    "alquiler de camiones volquete",
    "alquiler de torres de iluminación para obra",
    "alquiler de montacargas diesel",
    "alquiler de minicargadoras bobcat",
    "alquiler de apisonadoras manuales",
    "alquiler de equipos de demolición",
    "alquiler de manipuladoras telescópicas para construcción",
    "alquiler de sierras de pavimento",
    "alquiler de bombas de hormigón autopropulsadas",
    "alquiler de fresadoras para asfalto",
    "alquiler de compresores de ire industrial",
    "alquiler de zanjadoras para instalaciones",
    "alquiler de niveladoras láser topográficas",
    "alquiler de grupos electrógenos silenciosos para obra",
    "alquiler de carros de obra autopropulsados",
    "alquiler de maquinaria forestal",
    "alquiler de cortadoras de hormigón profesionales",
    "alquiler de equipos de perforación horizontal",
    "alquiler de pisones compactadores a gasolina",
    "alquiler de camiones grúa certificados",
    "alquiler de cisternas para agua",
    "alquiler de plataformas tijera eléctricas",
    "alquiler de minicargadoras orugas para laconstrucción",
    "alquiler cortadoras de juntas de pavimento",
    "alquiler de equipos de hidrolimpieza industrial",
    "alquiler de vibradores de hormigón eléctricos",
    "alquiler de motoniveladoras de 140 hp",
    "alquiler de dumpers articulados todo terreno",
    "alquiler de mezcladoras hormigón"
]

keywords_informacionales = [
    "cuánto cuesta alquilar una grúa torre",
    "mejores empresas alquiler maquinaria construcción",
    "qué maquinaria necesito para excavación",
    "precio alquiler mensual excavadora 20 toneladas",
    "requisitos para alquilar maquinaria pesada España",
    "diferencia entre alquilar y comprar maquinaria industrial",
    "cómo elegir empresa alquiler equipos construcción",
    "documentación necesaria alquiler maquinaria construcción",
    "seguros incluidos en alquiler maquinaria industrial",
    "mantenimiento maquinaria alquiler construcción",
    "ventajas alquiler maquinaria frente a compra",
    "cuánto cuesta alquilar excavadora semana",
    "qué incluye el alquiler de maquinaria industrial",
    "comparativa precios alquiler grúas",
    "normativa alquiler maquinaria pesada España",
    "cuándo conviene alquilar o comprar equipos construcción",
    "seguros obligatorios maquinaria alquiler obra",
    "certificaciones necesarias operar maquinaria alquilada",
    "tarifas alquiler maquinaria construcción 2025",
    "mantenimiento preventivo equipos alquiler construcción",
    "responsabilidades contrato alquiler maquinaria industrial",
    "diferencias alquiler maquinaria con sin operador",
    "inspecciones técnicas maquinaria alquiler",
    "qué revisar antes alquilar excavadora",
    "cláusulas importantes contrato alquiler equipos",
    "periodos mínimos alquiler maquinaria pesada",
    "garantías exigir empresa alquiler maquinaria",
    "comparador empresas alquiler equipos construcción",
    "opiniones empresas alquiler maquinaria",
    "checklist alquilar maquinaria construcción segura",
    "costes ocultos alquiler maquinaria industrial",
    "diferencia entre renting y alquiler maquinaria",
    "impuestos aplicables alquiler equipos construcción España",
    "bonificaciones alquiler largo plazo maquinaria",
    "flexibilidad contratos alquiler equipos industriales",
    "plazos entrega maquinaria alquiler",
    "disponibilidad maquinaria temporada alta construcción",
    "servicios adicionales empresas alquiler equipos",
    "transporte incluido precio alquiler maquinaria",
    "formación operadores maquinaria alquilada"
]

keywords_tipo_maquinaria = [
    "alquiler miniexcavadoras para jardines",
    "renta de bulldozers para movimiento de tierras",
    "alquiler carretillas elevadoras eléctricas",
    "alquiler hormigoneras industriales gran capacidad",
    "alquiler motoniveladora para caminos rurales",
    "alquiler martillos hidráulicos para demolición",
    "renta de equipos de pavimentación asfáltica",
    "alquiler generadores eléctricos para obra",
    "alquiler andamios metálicos certificados",
    "alquiler rodillos compactadores autopropulsados",
    "alquiler tractores oruga movimiento tierras",
    "renta de excavadoras hidráulicas 30 toneladas",
    "alquiler plataformas articuladas diesel",
    "alquiler perforadoras neumáticas demolición",
    "renta de compactadores placa vibrante",
    "alquiler grúas autopropulsadas 50 metros",
    "alquiler mezcladoras cemento portátiles",
    "renta de equipos izaje cargas pesadas",
    "alquiler rozadoras para túneles",
    "alquiler equipos cribado áridos",
    "renta de dragas excavación fluvial",
    "alquiler cargadoras frontales ruedas",
    "alquiler extendedoras asfalto autopropulsadas",
    "renta de equipos sondeo geotécnico",
    "alquiler camiones hormigonera 8m3",
    "alquiler equipos hincado pilotes",
    "renta de barredoras industriales autopropulsadas",
    "alquiler cintas transportadoras materiales",
    "alquiler torres andamio móviles aluminio",
    "renta de equipos pulido hormigón",
    "alquiler bombas achique aguas residuales",
    "alquiler trituradoras residuos construcción",
    "renta de equipos soldadura industrial",
    "alquiler remolques basculantes carga",
    "alquiler grúas pluma articulada",
    "renta de equipos ventilación obras subterráneas",
    "alquiler mesas vibrantes prefabricados",
    "alquiler equipos asfaltado en caliente",
    "renta de plataformas elevadoras brazo telescópico",
    "alquiler equipos compactación suelos"
]

keywords_proyecto_sector = [
    "alquiler maquinaria excavación sótanos",
    "equipos industriales construcción puentes",
    "maquinaria alquiler instalaciones solares",
    "alquiler equipos construcción túneles",
    "maquinaria industrial obras hidráulicas",
    "alquiler equipos construcción aparcamientos",
    "maquinaria pesada construcción aeropuertos",
    "alquiler equipos urbanización jardines",
    "maquinaria industrial construcción hospitales",
    "alquiler equipos obras marítimas portuarias",
    "maquinaria construcción instalaciones deportivas",
    "alquiler equipos rehabilitación edificios históricos",
    "maquinaria industrial construcción centros comerciales",
    "alquiler equipos instalación tuberías",
    "maquinaria construcción plantas industriales",
    "alquiler equipos cimentaciones especiales",
    "maquinaria industrial construcción depuradoras",
    "alquiler equipos obras ferroviarias",
    "maquinaria construcción parques eólicos",
    "alquiler equipos acondicionamiento terrenos",
    "maquinaria industrial desmonte explanaciones",
    "alquiler equipos construcción presas embalses",
    "maquinaria construcción gasolineras",
    "alquiler equipos obras alcantarillado",
    "maquinaria industrial pavimentación parkings",
    "alquiler equipos construcción muros contención",
    "maquinaria obras canalización redes",
    "alquiler equipos construcción rotondas",
    "maquinaria industrial demoliciones controladas",
    "alquiler equipos construcción hoteles",
    "alquiler maquinaria para reformas de edificios",
    "equipos industriales alquiler construcción piscinas",
    "maquinaria alquiler proyectos agrícolas",
    "alquiler equipos movimiento tierras urbanización",
    "maquinaria industrial para obras públicas",
    "alquiler maquinaria construcción naves industriales",
    "equipos alquiler para rehabilitación fachadas",
    "maquinaria pesada alquiler carreteras autopistas",
    "alquiler equipos construcción viviendas unifamiliares",
    "maquinaria industrial para polígonos industriales"
]

keywords_urgencia_flexibilidad = [
    "alquiler maquinaria construcción entrega inmediata",
    "alquiler maquinaria industrial sin permanencia",
    "empresas alquiler equipos disponibles 24 horas",
    "alquiler maquinaria construcción corto plazo",
    "renta maquinaria pesada servicio técnico incluido",
    "alquiler equipos industriales con seguro todo riesgo",
    "empresas alquiler maquinaria mantenimiento incluido",
    "alquiler maquinaria construcción transporte gratis",
    "renta equipos industriales contratos flexibles",
    "alquiler maquinaria pesada con operador certificado",
    "alquiler maquinaria construcción último minuto",
    "empresas alquiler equipos servicio 7 días",
    "renta maquinaria pesada cancelación gratis",
    "alquiler equipos industriales sin depósito",
    "empresas alquiler maquinaria facturación inmediata",
    "alquiler maquinaria construcción pago aplazado",
    "renta equipos industriales contrato mensual",
    "alquiler maquinaria pesada sin compromiso",
    "empresas alquiler equipos reposición garantizada",
    "alquiler maquinaria construcción entrega sábados",
    "renta equipos industriales soporte telefónico 24h",
    "alquiler maquinaria pesada reserva online",
    "empresas alquiler equipos descuento largo plazo",
    "alquiler maquinaria construcción tarifa cerrada",
    "renta equipos industriales ampliación periodo",
    "alquiler maquinaria pesada recambios incluidos",
    "empresas alquiler equipos asistencia técnica urgente",
    "alquiler maquinaria construcción sin gastos ocultos",
    "renta equipos industriales formación incluida",
    "alquiler maquinaria pesada devolución flexible",
    "empresas alquiler equipos inspección previa",
    "alquiler maquinaria construcción renovación automática",
    "renta equipos industriales carburante incluido",
    "alquiler maquinaria pesada servicio recogida",
    "empresas alquiler equipos descuento nuevos clientes",
    "alquiler maquinaria construcción paquetes obra",
    "renta equipos industriales precio todo incluido",
    "alquiler maquinaria pesada contratos temporada",
    "empresas alquiler equipos bonos prepago",
    "alquiler maquinaria construcción operador bilingüe"
]